version : '3.7'
services:
  db:
    image: surrealdb/surrealdb:latest
    restart: always
    command: start --user root --pass root memory
    ports:
      - '8000:8000'
    volumes:
      - db:/var/lib/surrealdb/data
    networks:
      - backend

  rest-api:
    image: rust-actix-surreal-rest-api
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db
    environment:
      - BASE_URL=http://172.26.0.2:8000
      - RUST_BACKTRACE=1

networks:
  backend:

volumes:
  db:
    driver: local
